# Generated by Django 6.0 on 2025-12-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products_in', to='Product.category'),
        ),
    ]
