# Generated by Django 6.0 on 2025-12-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
