# Generated by Django 5.2.3 on 2026-01-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cartitem_subtotal'),
        ('Product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='Product.product'),
        ),
    ]
